-- Insert missing service pages and projects page into page_seo table
INSERT INTO page_seo (page_slug, page_title, meta_title, meta_description, canonical_url, is_indexed, is_followed) VALUES
  ('3d-walkthrough-video', '3D Walkthrough Video', '3D Walkthrough Video Services | Real Estate Virtual Tours', 'Professional 3D walkthrough video services for real estate marketing. Immersive virtual tours and architectural animations to showcase your properties.', 'https://eastdigital.in/expertise/real-estate/3d-walkthrough-video', true, true),
  ('3d-still-renderings', '3D Still Renderings', '3D Still Renderings | Photorealistic Real Estate Visuals', 'High-quality 3D still renderings for real estate marketing. Photorealistic exterior and interior visualizations for properties and developments.', 'https://eastdigital.in/expertise/real-estate/3d-still-renderings', true, true),
  ('conceptual-3d-renderings', 'Conceptual 3D Renderings', 'Conceptual 3D Renderings | Infrastructure Project Visualization', 'Professional conceptual 3D renderings for infrastructure projects. Visualize bridges, roads, urban planning and development concepts.', 'https://eastdigital.in/expertise/infrastructure/conceptual-3d-renderings', true, true),
  ('engineering-3d-models', 'Engineering 3D Models', 'Engineering 3D Models | Technical Visualization Services', 'Precise engineering 3D models for technical and industrial projects. CAD modeling, technical drawings and engineering visualization.', 'https://eastdigital.in/expertise/infrastructure/engineering-3d-models', true, true),
  ('architectural-3d-rendering', 'Architectural 3D Rendering', 'Architectural 3D Rendering | Professional Building Visualization', 'Expert architectural 3D rendering services for buildings and structures. Photorealistic architectural visualizations for presentations and marketing.', 'https://eastdigital.in/expertise/architecture-design/architectural-3d-rendering', true, true),
  ('product-3d-rendering', 'Product 3D Rendering', 'Product 3D Rendering | Professional Product Visualization', 'High-quality product 3D rendering services for marketing and design. Photorealistic product visualizations for e-commerce and presentations.', 'https://eastdigital.in/expertise/architecture-design/product-3d-rendering', true, true),
  ('projects', 'Projects', 'Our Projects | 3D Visualization Portfolio | East Digital', 'Explore our portfolio of 3D visualization projects including architectural renderings, real estate marketing, and infrastructure visualizations.', 'https://eastdigital.in/projects', true, true)
ON CONFLICT (page_slug) DO NOTHING;